### ISSUE TITLE
No broadcast

### ISSUE THREAD

**Issue by fun4stuff** [braytonstafford/google-assistant-relay#1]
I have assistant relay server working with ifttt.

I installed the assistant-relay smart app on the web and in smartthings app.

I get no broadcast though.

**Comment by braytonstafford** [comment]
Are you running assistant relay server v2?

Also, after you installed the smartapp were you able to successfully input the server IP address and port in the settings for the smartapp?

**Comment by tenoriojuann** [comment]
I am seeing this issue as well.

I have just set up the assistant relay server v2. I am able to POST messages to the /assistant end point but my Google Home is not playing anything. The server response with an audio file that has the Google Assistant audio, somehow it is not making it to my google home

**Comment by Odono1** [comment]
Does the APP function correctly with Assistant Relay Server V3 ?  I have the relay working from my pc  and I also have the IP address and port set up in the smartapp. Thanks

**Comment by Odono1** [comment]
Please ignore my previous question. I have it all working, it was a firewall issue preventing the App working. Great Job by the way.
